/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALink: typeof import('@arco-design/web-vue')['Link']
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ASlider: typeof import('@arco-design/web-vue')['Slider']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATable: typeof import('@arco-design/web-vue')['Table']
    GeneralSettingsPanel: typeof import('./../components/pet-view/component/pet-bubble-settings/component/general-settings-panel/index.vue')['default']
    IconCheck: typeof import('@arco-design/web-vue/es/icon')['IconCheck']
    IconCheckCircle: typeof import('@arco-design/web-vue/es/icon')['IconCheckCircle']
    IconCloseCircle: typeof import('@arco-design/web-vue/es/icon')['IconCloseCircle']
    IconDelete: typeof import('@arco-design/web-vue/es/icon')['IconDelete']
    IconFile: typeof import('@arco-design/web-vue/es/icon')['IconFile']
    IconInfoCircle: typeof import('@arco-design/web-vue/es/icon')['IconInfoCircle']
    IconLeft: typeof import('@arco-design/web-vue/es/icon')['IconLeft']
    IconPlus: typeof import('@arco-design/web-vue/es/icon')['IconPlus']
    IconSafe: typeof import('@arco-design/web-vue/es/icon')['IconSafe']
    IconStop: typeof import('@arco-design/web-vue/es/icon')['IconStop']
    PetBubble: typeof import('./../components/pet-view/component/pet-bubble/index.vue')['default']
    PetBubbleActions: typeof import('./../components/pet-view/component/pet-bubble-actions/index.vue')['default']
    PetBubbleConfirm: typeof import('./../components/pet-view/component/pet-bubble-confirm/index.vue')['default']
    PetBubbleDrop: typeof import('./../components/pet-view/component/pet-bubble-drop/index.vue')['default']
    PetBubbleError: typeof import('./../components/pet-view/component/pet-bubble-error/index.vue')['default']
    PetBubbleProgress: typeof import('./../components/pet-view/component/pet-bubble-progress/index.vue')['default']
    PetBubbleRecords: typeof import('./../components/pet-view/component/pet-bubble-records/index.vue')['default']
    PetBubbleResult: typeof import('./../components/pet-view/component/pet-bubble-result/index.vue')['default']
    PetBubbleSettings: typeof import('./../components/pet-view/component/pet-bubble-settings/index.vue')['default']
    PetView: typeof import('./../components/pet-view/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsCard: typeof import('./../components/pet-view/component/pet-bubble-settings/component/settings-card/index.vue')['default']
    ShredRecordPanel: typeof import('./../components/pet-view/component/pet-bubble-records/component/shred-record-panel/index.vue')['default']
    SvgIcon: typeof import('./../components/svg-icon/index.vue')['default']
  }
}
