/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALink: typeof import('@arco-design/web-vue')['Link']
    APagination: typeof import('@arco-design/web-vue')['Pagination']
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm']
    AppearanceSetting: typeof import('./../components/pet-view/component/pet-bubble-settings/component/appearance-setting/index.vue')['default']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATrigger: typeof import('@arco-design/web-vue')['Trigger']
    PetBubble: typeof import('./../components/pet-view/component/pet-bubble/index.vue')['default']
    PetBubbleAction: typeof import('./../components/pet-view/component/pet-bubble-actions/component/pet-bubble-action/index.vue')['default']
    PetBubbleActions: typeof import('./../components/pet-view/component/pet-bubble-actions/index.vue')['default']
    PetBubbleActionsHeader: typeof import('./../components/pet-view/component/pet-bubble-actions/component/pet-bubble-actions-header/index.vue')['default']
    PetBubbleActionsTip: typeof import('./../components/pet-view/component/pet-bubble-actions/component/pet-bubble-actions-tip/index.vue')['default']
    PetBubbleConfirm: typeof import('./../components/pet-view/component/pet-bubble-confirm/index.vue')['default']
    PetBubblePageHeader: typeof import('./../components/pet-view/component/pet-bubble-page-header/index.vue')['default']
    PetBubbleProgress: typeof import('./../components/pet-view/component/pet-bubble-progress/index.vue')['default']
    PetBubbleRecords: typeof import('./../components/pet-view/component/pet-bubble-records/index.vue')['default']
    PetBubbleResult: typeof import('./../components/pet-view/component/pet-bubble-result/index.vue')['default']
    PetBubbleSettings: typeof import('./../components/pet-view/component/pet-bubble-settings/index.vue')['default']
    PetCharacter: typeof import('./../components/pet-view/component/pet-character/index.vue')['default']
    PetCharacterDrag: typeof import('./../components/pet-view/component/pet-character/component/pet-character-drag/index.vue')['default']
    PetView: typeof import('./../components/pet-view/index.vue')['default']
    RecordEmptyState: typeof import('./../components/pet-view/component/pet-bubble-records/component/record-empty-state/index.vue')['default']
    RecordStatusCell: typeof import('./../components/pet-view/component/pet-bubble-records/component/record-status-cell/index.vue')['default']
    RecordTargetCell: typeof import('./../components/pet-view/component/pet-bubble-records/component/record-target-cell/index.vue')['default']
    SettingsCard: typeof import('./../components/pet-view/component/pet-bubble-settings/component/settings-card/index.vue')['default']
    SettingsLayoutRow: typeof import('./../components/pet-view/component/pet-bubble-settings/component/appearance-setting/component/settings-layout-row/index.vue')['default']
    ShredLevelSetting: typeof import('./../components/pet-view/component/pet-bubble-settings/component/shred-level-setting/index.vue')['default']
    SvgIcon: typeof import('./../components/svg-icon/index.vue')['default']
    SystemSetting: typeof import('./../components/pet-view/component/pet-bubble-settings/component/system-setting/index.vue')['default']
  }
}
